### ISSUE TITLE
django-sslify Usage with Cloudflare

### ISSUE THREAD

**Issue by JeffPaine** [rdegges/django-sslify#2]
Apologies in advance if this isn't the appropriate place to note the following.

When using `django-sslify` with an app behind Cloudflare, you have to have the [Cloudflare SSL option](https://support.cloudflare.com/entries/22046881-what-do-the-three-ssl-options-off-flexible-full-mean) set to "Full SSL" (or possibly "Off", but I'm unable to test that).

![Screenshot_3_6_13_7_44_AM](https://f.cloud.github.com/assets/1269165/227369/de24797c-865b-11e2-9a2f-430b7aec8228.png)

This is because if you have the Cloudflare SSL option set to "Flexible", even if the user specifies an HTTPS connection, Cloudflare will then connect to your app without SSL (see image above) and `HTTP_X_FORWARDED_PROTO` will be set to `http`. This will cause an infinite redirect loop as `django-sslify` attempts to redirect the connection to HTTPS - starting the whole loop over again.

Whether this is worth noting in the README or better to close this issue as a record for others to find via google, I'll leave to you @rdegges :smiley:

**Comment by JeffPaine** [comment]
> But I'm sure people will at least find this useful when searching!

So, I was working through this issue today (a config issue, not the "fault" of django-sslify), and I'm searching GH and I find this very issue that I wrote up myself two years ago! Funny how time flies, the mind forgets and web (thankfully) doesn't. Cheers!

**Comment by rdegges** [comment]
I've had this same experience recently -- pretty odd!

<333 github issues
