### ISSUE TITLE
When debug turned off with nginx receive Infinite 301 Error.

### ISSUE THREAD

**Issue by beneshed** [rdegges/django-sslify#23]
I spent hours trying to debug this.

In Nginx I have port 80 redirecting to port 443. I attempted to turn off debug and I would always got an infinite 301 loop. My fix was to uninstall django-sslify and it worked fine!

Did I do anything wrong?

**Comment by kokeshii** [comment]
Hi, I was having exactly the same issue. I kept on googling and luckily I found the solution on this stackoverflow thread http://stackoverflow.com/questions/23121800/nginx-redirect-loop-with-ssl.

The solution was to add this line:
    proxy_set_header        X-Forwarded-Proto $scheme;

To muy nginx.conf file.

You might want to add this to the readme.
Thank you for your time devoted to this project.

**Comment by rdegges** [comment]
CARLO. Thanks man! I'll add that now.

**Comment by rdegges** [comment]
Just pushed info into the readme. Will deploy to master once I get some more stuff in there for a proper release.
