### ISSUE TITLE
Unable to render templates

### ISSUE THREAD

**Issue by jsetting32** [rdegges/django-sslify#26]
Hi Randall,

I am attempting to use this middleware but am having some issues. I added the middleware to my middleware classes (first in the list), and set my application to DEBUG=False. But I am currently unable to render any templates, or rather keep getting this message:

```
[27/Mar/2015 18:21:27] code 400, message Bad request syntax ('\x16\x03\x01\x00\xaf\x01\x00\x00\xab\x03\x03U\x15\x9f\xa7\xa1\xaf\xf3\xb5s\x17/i\x96-\xee\xeb\xcb\x11\xc5\xb7\x81\xef\xc8\x9a\xdc\xd4/\xc2\x039\xd6\x96\x00\x00J\x00\xff\xc0$\xc0#\xc0')
```

I read up on a StackOverflow post saying this is related to HTTPS requests but of course, need HTTPS to work for my Django Web App. Any ideas on how to fix this?

**Comment by rdegges** [comment]
I'm not sure, this is the first time I've seen this. It looks as if you're accepting HTTPS requests DIRECTLY to your Django process, as opposed to having some sort of webserver / proxy intercept the SSL before passing the request to Django.

If that's what you're doing, you should really be using a web server of some sort in front of your Django app:

- gunicorn
- nginx
- something

**Comment by jsetting32** [comment]
Hi Randall,

Thank you for the quick response!

I read upon nginx and set it up but am not running it. I ran through a tutorial on uWSGI and nginx but wasn’t able to link the two together. This is the link I followed for the tutorial : http://uwsgi-docs.readthedocs.org/en/latest/tutorials/Django_and_nginx.html <http://uwsgi-docs.readthedocs.org/en/latest/tutorials/Django_and_nginx.html> 

Is this going to put me on the right track? What would you recommend between the two (gunicorn vs nginx) ?

**Comment by rdegges** [comment]
I'm really only familiar with gunicorn, which is what I use. There are benefits / drawbacks to all of the different web servers, but in reality it doesn't matter so long as the webeserver itself is what's terminating the SSL connection.

I can't really speak to whether or not that tutorial is gonna help you though, sorry :(

You might be better off trying stackoverflow or something like that for this sort of help, as I'm sorta useless ><

**Comment by jsetting32** [comment]
Its no problem. 

Thanks for your feedback, I greatly appreciate it!

**Comment by raul1991** [comment]
Hi randall,
Can you explain why django server should not be handling direct https connections ? Or some link

**Comment by rdegges** [comment]
It's not so much that the Django server shouldn't be terminating the SSL -- it's moreso a matter of speed and efficiency. EG: An actual webserver is going to be MUCH faster at handling the crypto operations, and this will also spare your Django process itself the pain of doing crypto on top of every connection.

AFAIK, this is the 'best practice' for scripting languages like Python where you're stuck on a single processor.
