### ISSUE TITLE
All files in my static folder are returning 404 when sslify is enabled.

### ISSUE THREAD

**Issue by brspurri** [rdegges/django-sslify#29]
This library looks like it could be quite useful.

However, I'm finding that everything in my `static` fold is 404'ing when I enable **django-sslify**. 
So all my css is being lost.

Have you seen this behavior before?

**Comment by brspurri** [comment]
Turns out to have nothing to do this sslify. Needed to `collectstatic` when `DEBUG=False`.

**Comment by rdegges** [comment]
Glad things are working for ya! ^^
