### ISSUE TITLE
Obsolete for Django >= 1.8?

### ISSUE THREAD

**Issue by dfrankow** [rdegges/django-sslify#31]
Does http://stackoverflow.com/a/26670053/34935 mean this library is now in core Django as of 1.8?

**Comment by rdegges** [comment]
That's correct! I'd love to finally retire this. Right now I'm keeping it open as older Django users might need this.

But this is correct: in 1.8 you can use the built-in stuff.

**Comment by dfrankow** [comment]
Thanks!

**Comment by bengolder** [comment]
Just noticed this closed issue after wondering the same thing. I think I'll add a PR for future users.
